name: currybot
services:
  node:
    type: node:10.14.2
    build:
      - npm install -g node-gyp
      - npm install
      - node-gyp configure build
tooling:
  node:
    service: node
  npm:
    service: node
  node-gyp:
    service: node

