version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules